---
name: Autobuild our image
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{
          secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build healthcheck
        run: |
          docker buildx build --push -f docker/BuildHealthCheck.Dockerfile \
            --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
            -t sofiaurora/dockge:build-healthcheck .
      - name: build base
        run: |
          docker buildx build --push -f ./docker/Base.Dockerfile \
          --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
          -t sofiaurora/dockge:base .
      - name: build the image
        run: |
          node ./extra/env2arg.js docker buildx build --push -f ./docker/Dockerfile \
          --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
          -t sofiaurora/dockge:latest --target release .

          docker buildx build --push \
            --tag forgenator/monitor.sh:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 .
